name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        kubernetes-version: ['1.15.12', '1.16.15', '1.17.11', '1.18.8', '1.19.1']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m lightkube-generate resources models openapi/kubernetes_v${{ kubernetes-version }}.json
    - name: Test
      run: |
        python test_models.py
        python test_resources.py
    - name: Package
      run: |
        pip install wheel
        python setup.py bdist_wheel
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: v${{ kubernetes-version }}
        path: |
          dist


